name: "DOcker BUild and Deploy"

on:
  push:
    branches:
      - "ci/rabin-cicd"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: "ci/rabin-cicd"
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: Docker build
        run: |
          echo "BUild DOcker Images"
          docker build -t rabindangolrd/entvscmd .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Images
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/entvscmd
