name: "Docker build and deploy"
on:
 push:
   branches:
   - "main"
   - "develop"
   - "ci/add-cicd-sabin"

jobs:
 build:
   runs-on: ubuntu-latest
   environment: ci/add-cicd-sabin
   steps:
     - name: Checkout repository
       uses: actions/checkout@v2
     - name: Docker build
       run: |
         echo "Building Docker images"
         docker build -t sabin30/dockerlabaug .


   
