name: "Docker build and deploy"
on:
 push:
   branches:
   - "main"
   - "develop"
   - "ci/add-cicd-sabin"

jobs:
 build:
   runs-on: ubuntu-latest
   environment: ci/add-cicd-sabin
   steps:
     - name: Checkout repository
       uses: actions/checkout@v2
     - name: Docker build
       run: |
         echo "Building Docker images"
         docker build -t sabin30/dockerlabaug .
     - name: Login to Docker Hub
       uses: docker/login-action@v3
       with:
         username: ${{ vars.DOCKERHUB_USERNAME }}
	 password: ${{ secrets.DOCKERHUB_TOKEN }}    
     - name: Push Images
       run: docker push ${{ vars.DOCKERHUB_USERNAME }}/dockerlabaug     


   
